// <auto-generated />
using System;
using CondominioApp.Portaria.Infra.DataQuery;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CondominioApp.Portaria.Infra.Migrations.PortariaQueryContextDBMigrations
{
    [DbContext(typeof(PortariaQueryContextDB))]
    [Migration("20210720161350_CriadorDoVisitanteFlat")]
    partial class CriadorDoVisitanteFlat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CondominioApp.Portaria.Domain.FlatModel.VisitaFlat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AndarUnidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorVeiculo")
                        .HasColumnName("Cor")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeSaida")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoTipoDeDocumentoVisitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoTipoDeVisitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoVisitante")
                        .HasColumnName("Documento")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("EmailVisitante")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("FotoVisitante")
                        .HasColumnName("Foto")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("GrupoUnidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Lixeira")
                        .HasColumnType("bit");

                    b.Property<string>("ModeloVeiculo")
                        .HasColumnName("Modelo")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("NomeCondominio")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeEmpresaVisitante")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeVisitante")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumeroUnidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PlacaVeiculo")
                        .HasColumnName("Placa")
                        .HasColumnType("varchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("TemVeiculo")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDeDocumentoVisitante")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TipoDeVisitante")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VisitasFlat");
                });

            modelBuilder.Entity("CondominioApp.Portaria.Domain.FlatModel.VisitanteFlat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AndarUnidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoTipoDeDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoTipoDeVisitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnName("Documento")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("GrupoUnidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Lixeira")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeArquivoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCondominio")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeDoCriador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeOriginalArquivoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroUnidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("QrCode")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("TemVeiculo")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TipoDeUsuarioDoCriador")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeVisitante")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("VisitantePermanente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("VisitantesFlat");
                });
#pragma warning restore 612, 618
        }
    }
}
